import runpy
import sys
from pathlib import Path
from typing import Any, Self

from ninja import Writer

from bob.constants import (
    BOB_BUILDDIR_SUBDIRECTORY,
    get_build_ninja_path,
    get_compdb_ninja_path,
    get_configs_path,
    get_used_configs_path,
)


class Context:
    _CURRENT: None | Self = None

    def __init__(self, builddir: Path, configs: dict[str, str]):
        from bob.api.rule import PhonyTarget

        self.builddir = builddir
        self.configs = configs
        self.used_configs: set[str] = set()
        self.writer: None | Writer = None
        self.compdb_writer: None | Writer = None
        self.configure_implicit_dependencies = {get_configs_path(builddir)}
        self.variables: dict[str, Any] = {}
        self.bobfile: None | Path = None
        self.always: PhonyTarget | None = None

    def __enter__(self) -> Self:
        assert Context._CURRENT is None

        (self.builddir / BOB_BUILDDIR_SUBDIRECTORY).mkdir(parents=True, exist_ok=True)

        self.writer = Writer(
            open(get_build_ninja_path(self.builddir), "w"),  # ty: ignore[invalid-argument-type]
            width=999999,
        )
        self.compdb_writer = Writer(
            open(get_compdb_ninja_path(self.builddir), "w"),  # ty: ignore[invalid-argument-type]
            width=999999,
        )

        self.writer.comment("This file was automatically generated by Bob.")
        self.writer.variable("builddir", str(self.builddir / BOB_BUILDDIR_SUBDIRECTORY))

        Context._CURRENT = self

        from bob.api.rule import phony

        self.always = phony(str(self.builddir / BOB_BUILDDIR_SUBDIRECTORY / "always"))

        self.writer.newline()

        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        failed = exc is not None
        from bob.api.rule import Rule

        Rule(
            "FORCE_COLOR=1 $bobbin configure --use-current-configs -f $bobfile",
            description="CONFIGURE",
            generator=True,
            pool="console",
        ).build(
            str(get_build_ninja_path(self.builddir).relative_to(self.builddir)),
            implicit=list(sorted(str(d) for d in self.configure_implicit_dependencies)),
            variables={
                "bobbin": f"{sys.executable} -m bob",
                "bobfile": str(self.bobfile),
            },
        )

        get_used_configs_path(self.builddir).write_text(
            "\n".join(sorted(self.used_configs))
        )

        try:
            for key in self.configs:
                assert key in self.used_configs, f'Invalid config "{key}"'
        except AssertionError:
            failed = True
            raise
        finally:
            assert self.writer is not None
            assert self.compdb_writer is not None
            self.writer.close()
            self.writer = None
            self.compdb_writer.close()
            self.compdb_writer = None

            if failed:
                get_build_ninja_path(self.builddir).unlink()
                get_compdb_ninja_path(self.builddir).unlink()

            assert Context._CURRENT is self
            Context._CURRENT = None

    @staticmethod
    def current() -> "Context":
        result = Context._CURRENT
        assert result is not None
        return result

    def evaluate(self, bobfile: Path) -> None:
        if self.bobfile is None:
            self.bobfile = bobfile

        self.configure_implicit_dependencies.add(bobfile)
        runpy.run_path(str(bobfile))
